//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersDataEntities : DbContext
    {
        public UsersDataEntities()
            : base("name=UsersDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Exam1> Exam1 { get; set; }
        public DbSet<Exam2> Exam2 { get; set; }
        public DbSet<Exam3> Exam3 { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
