//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string Course { get; set; }
        public int ClassNumber { get; set; }
        public decimal TotalGrade { get; set; }
        public string ChapterName { get; set; }
        public int ExamID { get; set; }
        public string Username { get; set; }
    }
}
